Press_Agency_System/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Press_Agency_System.Models;
using Press_Agency_System.Observer;
using Press_Agency_System.Services;

namespace Press_Agency_System.Controllers
{
    [Authorize(Roles = "Admin,Editor,Viewer")]
    public class PostController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult AllUsers()
        {
            var posts = db.Users.Include(x => x.Roles).ToList();

            return Json(new { data = posts }, JsonRequestBehavior.AllowGet);

        }


        //[Authorize]
        public ActionResult AllPosts()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var posts = db.Posts.Include(x => x.User);
            return Json(new { data = posts }, JsonRequestBehavior.AllowGet);

        }
        //[Authorize]
        public ActionResult AllPostsForEditor(string UserId)
        {
            var posts = db.Posts.Where(e => e.UserId == UserId).ToList();
            return Json(new { data = posts }, JsonRequestBehavior.AllowGet);

        }

        // GET: /Post/
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.User);
            return View(posts.ToList());
        }

        // GET: /Post/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Include(e => e.User).SingleOrDefault(x => x.Id == id);

            if (post == null )
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();

            if ((post.State == PostState.Waiting || post.State == PostState.Rejected) && !isAuthorized(userId))
            {
                return HttpNotFound();
            }

            
            List<InteractedPosts> allposts = db.IneractedPosts.Where(e => e.PostId == id).ToList();
            var obj = allposts.Find(e => e.UserId == userId) as InteractedPosts;
            byte likedbyuser;
            if (obj == null)
                likedbyuser = 0;
            else
                likedbyuser = obj.Like;


            var objsaved = db.SavedPosts.FirstOrDefault(e => e.PostId == id && e.UserId == userId) as SavedPosts;
            var savedbyuser = false;
            if (objsaved != null)
            {
                savedbyuser = true;
            }

            PostDetailsViewModel pdvm = new PostDetailsViewModel()
            {
                allInteractions = allposts,
                Post = post,
                likedbyuser = likedbyuser,
                saveedbyuser = savedbyuser
            };

            return View(pdvm);
        }
        [Authorize (Roles="Admin,Editor")]
        // GET: /Post/Create
        public ActionResult Create()
        {
            ViewBag.PostCategories = PostCategories.AllCategories;
            return View();
        }

        // POST: /Post/Create
        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, HttpPostedFileBase UploadedImage)
        {
            ViewBag.PostCategories = PostCategories.AllCategories;
            if (ModelState.IsValid)
            {
                if (UploadedImage != null)
                {
                    var path = System.IO.Path.Combine(Server.MapPath("~/Content/Posts Images"), UploadedImage.FileName);
                    UploadedImage.SaveAs(path);
                    post.ImagePath = UploadedImage.FileName;
                }
                else
                {
                    post.ImagePath = "DefaultImageForPost.jpg";
                }

                post.UserId = User.Identity.GetUserId();
                post.IsActive = true;
                post.State = PostState.Waiting;

                post.PostDate = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: /Post/Edit/5
        [Authorize(Roles = "Admin,Editor")]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.PostCategories = PostCategories.AllCategories;
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string rolename = userManager.GetRoles(User.Identity.GetUserId()).FirstOrDefault();
            if (rolename == "Editor")
            {
                if (User.Identity.GetUserId() != post.UserId)
                {
                    return HttpNotFound();
                }
            }

            return View(post);
        }

        // POST: /Post/Edit/5


        [Authorize(Roles = "Admin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post, HttpPostedFileBase UploadedImage)
        {
            ViewBag.PostCategories = PostCategories.AllCategories;
            var oldpost = db.Posts.FirstOrDefault(e => e.Id == post.Id);
            if (ModelState.IsValid)
            {
                if (UploadedImage != null)
                {
                    var path = System.IO.Path.Combine(Server.MapPath("~/Content/Posts Images"), UploadedImage.FileName);
                    UploadedImage.SaveAs(path);
                    oldpost.ImagePath = UploadedImage.FileName;
                }

                oldpost.IsActive = true;
                oldpost.State = PostState.Waiting;
                oldpost.PostDate = DateTime.Now;
                oldpost.PostTitle = post.PostTitle;
                oldpost.PostBody = post.PostBody;
                oldpost.PostType = post.PostType;


                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: /Post/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult ViewPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            var react = new InteractedPosts();
            react.PostId = post.Id;
            react.UserId = User.Identity.GetUserId();
            react.Like = 0;
            var interactedpost = db.IneractedPosts.FirstOrDefault(x => x.UserId == react.UserId && x.PostId == react.PostId) as InteractedPosts;
            if (interactedpost != null)
            {
                return Content("0");
            }
            else
            {
                db.IneractedPosts.Add(react);
                db.SaveChanges();
                return Content("1");
            }

        }


        public ActionResult Like(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            var react = new InteractedPosts();
            react.PostId = post.Id;
            react.UserId = User.Identity.GetUserId();
            react.Like = 1;
            var interactedpost = db.IneractedPosts.FirstOrDefault(x => x.UserId == react.UserId && x.PostId == react.PostId);
            if (interactedpost != null)
            {
                if (interactedpost.Like == 2)
                {
                    interactedpost.Like = 1;
                    db.Entry(interactedpost).State = EntityState.Modified;
                    db.SaveChanges();
                    return Content("1");
                }
                else if (interactedpost.Like == 0)
                {
                    interactedpost.Like = 1;
                    db.Entry(interactedpost).State = EntityState.Modified;
                    db.SaveChanges();
                    return Content("1");
                }
                else
                {
                    interactedpost.Like = 0;
                    db.Entry(interactedpost).State = EntityState.Modified;
                    db.SaveChanges();
                    return Content("-1");
                }

            }
            else
            {
                db.IneractedPosts.Add(react);
                db.SaveChanges();
                return Content("1");
            }

        }
        public ActionResult disLike(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            var react = new InteractedPosts();
            react.PostId = post.Id;

Press_Agency_System/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Press_Agency_System.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Press_Agency_System.Controllers
{

    public class UserController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        static public List<String> RolesName = new List<string>(new string[] { "Admin", "Editor", "Viewer" });




        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
        // GET: User
        //public ActionResult index()
        //{

        //    return View();
        //}
        [Authorize(Roles = "Admin")]
        public ActionResult AllUsers()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var allusers = db.Users.Include(e => e.roleType).Where(x => x.activeUser == true).ToList();
            return Json(new { data = allusers }, JsonRequestBehavior.AllowGet);

        }



        public ActionResult AddUser(ApplicationUser userObj, string userrole, HttpPostedFileBase UploadedImage)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            if (ModelState.IsValid)
            {
                if (UploadedImage != null)
                {
                    var path = System.IO.Path.Combine(Server.MapPath("~/Content/Persons Images"), UploadedImage.FileName);
                    UploadedImage.SaveAs(path);
                    userObj.PhotoPath = UploadedImage.FileName;
                }
                else
                {
                    userObj.PhotoPath = "defaultuserphoto.jpg";
                }
                userObj.activeUser = true;
                userObj.roleType = db.Roles.FirstOrDefault(x => x.Name == userrole);

                var flag = userManager.Create(userObj, userObj.PasswordHash);
                if (flag.Succeeded)
                {
                    if (userrole == "Admin")
                    {
                        userManager.AddToRole(userObj.Id, Roles.Admin);
                        userObj.roleType.Name = "Admin";

                    }
                    else if (userrole == "Editor")
                    {
                        userManager.AddToRole(userObj.Id, Roles.Editor);
                        userObj.roleType.Name = "Editor";
                    }
                    else if (userrole == "Viewer")
                    {
                        userManager.AddToRole(userObj.Id, Roles.Viewer);
                        userObj.roleType.Name = "Viewer";
                    }
                    TempData["mess"] = "user added correctly";
                    return RedirectToAction("Index");
                }

                TempData["mess"] = "invaild username or password";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["mess"] = "invaild username or password";
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult index(string id)
        {
            if (id == null)
            {
                return View();
            }

            ApplicationUser obj = db.Users.Find(id);
            if (obj == null)
            {
                return HttpNotFound();
            }

            return View(obj);
        }
        [Authorize(Roles = "Admin,Editor,Viewer")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser obj = db.Users.Find(id);
            if (obj == null)
            {
                return HttpNotFound();
            }

            //  ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", obj.UserId);
            return View(obj);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Editor,Viewer")]
        public ActionResult Edit([Bind(Include = "Id,UserName,FirstName,LastName,Email,Phone,PhotoPath,roleType,activeUser")] ApplicationUser obj, HttpPostedFileBase UploadedImage, string userrole)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            if (ModelState.IsValid)
            {

                if (UploadedImage != null)
                {
                    var path = System.IO.Path.Combine(Server.MapPath("~/Content/Persons Images"), UploadedImage.FileName);
                    UploadedImage.SaveAs(path);
                    obj.PhotoPath = UploadedImage.FileName;

                }
                else
                {
                    obj.PhotoPath = "defaultuserphoto.jpg";
                }
                obj.activeUser = true;
                obj.roleType = db.Roles.FirstOrDefault(x => x.Name == userrole);
                var dotuse = db.Users.Include(x => x.roleType).FirstOrDefault(e => e.Id == obj.Id);
                userManager.RemoveFromRole(dotuse.Id, dotuse.roleType.Name);
                if (userrole == "Admin")
                {
                    userManager.AddToRole(obj.Id, Roles.Admin);
                    obj.roleType.Name = "Admin";

                }
                else if (userrole == "Editor")
                {
                    userManager.AddToRole(obj.Id, Roles.Editor);
                    obj.roleType.Name = "Editor";
                }
                else if (userrole == "Viewer")
                {
                    userManager.AddToRole(obj.Id, Roles.Viewer);
                    obj.roleType.Name = "Viewer";
                }
                updatfunc(obj);
                return RedirectToAction("Index");
            }


            return View(obj);
        }

        private void updatfunc(ApplicationUser obj)
        {
            ApplicationUser existing = db.Users.Find(obj.Id);

            ((IObjectContextAdapter)db).ObjectContext.Detach(existing);


            db.Entry(obj).State = EntityState.Modified;

            db.SaveChanges();
        }
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser obj = db.Users.Find(id);
            if (obj == null)
            {
                return HttpNotFound();
            }
            return View(obj);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser obj = db.Users.FirstOrDefault(x => x.Id == id);
            obj.activeUser = false;

            db.Entry(obj).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

//[HttpPost, ActionName("Delete")]
//public ActionResult DeleteConfirmed(string id)
//{
//    ApplicationUser obj = db.Users.Find(id);
//    db.Users.Remove(obj);
//    db.SaveChanges();
//    return RedirectToAction("Index");
//}

Press_Agency_System/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/Content/footer-Dashboard-style.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />

    <title>@ViewBag.Title - Press Agency</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Press Agency", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Profile", "Profile", "Account")</li>
                    <li>@Html.ActionLink("User Page", "Index", "User")</li>
                    <li>@Html.ActionLink("Post Page", "Index", "Post")</li>
                    <li>@Html.ActionLink("Post Request", "Moderation", "Post")</li>
                    <li>@Html.ActionLink("Messages", "Messages", "Message")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <!-- Footer -->
    @*<footer class="footer1" style=" width: 100%; bottom: 0; height:93px; margin-bottom:0px;position:fixed;">
            <div class="container" style="padding: 15px 0;" align="center">
                <a href="#" style="        margin: 10px;">
                    <i class="fa fa-facebook fa-lg white-text mr-md-5 mr-3 fa-x"></i>
                </a>
                <a href="#" style="        margin: 10px;">
                    <i class="fa fa-twitter fa-lg white-text mr-md-5 mr-3 fa-x"></i>
                </a>
                <a href="#" style="        margin: 10px;">
                    <i class="fa fa-google-plus fa-lg white-text mr-md-5 mr-3 fa-x"></i>
                </a>
                <a href="#" style="        margin: 10px;">
                    <i class="fa fa-linkedin fa-lg white-text mr-md-5 mr-3 fa-x"></i>
                </a>
                <a href="#" style="        margin: 10px;">
                    <i class="fa fa-instagram fa-lg white-text mr-md-5 mr-3 fa-x"></i>
                </a>
                <a href="#" style="margin:10px;">
                    <i class="fa fa-pinterest fa-lg white-text"></i>
                </a>
            </div>
            <div class="bg-dark" style="background:black;">
                <p style="color: #91BEC2; padding: 15px 0;" align="center">
                    &copy; @DateTime.Now.Year Copyright: <a href="#">Created By: 5M Team</a>
                </p>
            </div>
        </footer>*@
    <footer>
        <center><p>&copy; @DateTime.Now.Year - 5M Team</p></center>
    </footer>
    <!-- Footer -->



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Press_Agency_System/Views/Shared/_FactoryLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<link rel="stylesheet" href="~/Content/footer-style.css" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link rel="stylesheet" href="~/Content/footer-style-Factory.css" />
    <title>@ViewBag.Title - Press Agency</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")




    <style>
        @@import url(http://fonts.googleapis.com/css?family=Lato);


        .side-bar {
            background: #74AFAD;
            position: fixed;
            height: 100%;
            width: 200px;
            color: #fff;
            transition: margin-left 0.5s;
        }

            .side-bar ul {
                list-style: none;
                padding: 0px;
            }

                .side-bar ul li.menu-head {
                    font-family: 'Lato', sans-serif;
                    padding: 20px;
                }


                    .side-bar ul li.menu-head a {
                        color: #fff;
                        text-decoration: none;
                        height: 50px;
                    }


                .side-bar ul .menu-head a {
                    color: #fff;
                    text-decoration: none;
                    height: 50px;
                }

                .side-bar ul .menu li a {
                    color: #fff;
                    text-decoration: none;
                    display: inline-table;
                    width: 100%;
                    padding-left: 20px;
                    padding-right: 20px;
                    padding-top: 10px;
                    padding-bottom: 10px;
                }

                    .side-bar ul .menu li a:hover {
                        border-left: 3px solid #ECECEA;
                        padding-left: 17px;
                    }

                    .side-bar ul .menu li a.active {
                        padding-left: 17px;
                        background: #D9853B;
                        border-left: 3px solid #ECECEA;
                    }

                        .side-bar ul .menu li a.active:before {
                            content: "";
                            position: absolute;
                            width: 0;
                            height: 0;
                            border-top: 20px solid transparent;
                            border-bottom: 20px solid transparent;
                            border-left: 7px solid #D9853B;
                            margin-top: -10px;
                            margin-left: 180px;
                        }


        .content {
            padding-left: 200px;
            transition: padding-left 0.5s;
        }

        .active > .side-bar {
            margin-left: -150px;
            transition: margin-left 0.5s;
        }

        .active > .content {
            padding-left: 50px;
            transition: padding-left 0.5s;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Press Agency", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>



    <div class="wrapper" id="content-wrapper">
        <!-- Sidebar -->
        <div class="side-bar">
            <ul>
                <li class="menu-head">
                    Press Agency <a href="#" class="push_menu" id="pushmenu" onclick="toggleSideBar()"><span class="glyphicon glyphicon-align-justify pull-right"></span></a>
                </li>
                <div class="menu">
                    <li>
                        @if (HttpContext.Current.Request.Url.AbsolutePath == "/Account/Profile")
                        {
                            <a href="@Url.Action("Profile","Account")" class="active">Profile <span class="glyphicon glyphicon-user pull-right"></span></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Profile","Account")">Profile <span class="glyphicon glyphicon-user pull-right"></span></a>
                        }

                    </li>
                    <li>
                        @if (HttpContext.Current.Request.Url.AbsolutePath == "/Post/Create")
                        {
                            <a href="@Url.Action("Create","Post")" class="active">Create New Post <span class="glyphicon glyphicon-plus-sign pull-right"></span></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Create","Post")">Create New Post <span class="glyphicon glyphicon-plus-sign pull-right"></span></a>

                        }

                    </li>
                    <li>
                        @if (HttpContext.Current.Request.Url.AbsolutePath == "/Post")
                        {
                            <a href="@Url.Action("Index","Post")" class="active">My Posts <span class="glyphicon glyphicon-paperclip pull-right"></span></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Index","Post")">My Posts <span class="glyphicon glyphicon-paperclip pull-right"></span></a>
                        }

                    </li>
                    <li>
                        @if (HttpContext.Current.Request.Url.AbsolutePath == "/Message/Messages")
                        {
                            <a href="~/Message/Messages" class="active">Received Questions <span class="glyphicon glyphicon-question-sign pull-right"></span></a>
                        }
                        else
                        {
                            <a href="~/Message/Messages">Received Questions <span class="glyphicon glyphicon-question-sign pull-right"></span></a>
                        }

                    </li>
                    <li>
                        @if (HttpContext.Current.Request.Url.AbsolutePath == "/Post/SavedPosts")
                        {
                            <a href="@Url.Action("SavedPosts","Post")" class="active">Saved Posts <i class="fas fa-save pull-right"></i></a>
                        }
                        else
                        {
                            <a href="@Url.Action("SavedPosts","Post")">Saved Posts <i class="fas fa-save pull-right"></i></a>   
                        }

                    </li>
                </div>

            </ul>
        </div>
        <!--/Sidebar-->
        <!-- Page Content -->
        <div class="content" style="margin-left:10px;">
            @RenderBody()
        </div>
    </div>


    <script>
        function toggleSideBar() {
            var element = document.getElementById("content-wrapper");
            element.classList.toggle("active");
        }
    </script>


    <!-- Footer -->
    <footer>
        <center><p>&copy; @DateTime.Now.Year - 5M Team</p></center>
    </footer>
    <!-- /Footer -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>